apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-jobs
subjects:
  - kind: ServiceAccount
    name: svc-infra-user
    apiGroup: ""
roleRef:
  kind: Role
  name: infra-jobs-read
  apiGroup: rbac.authorization.k8s.io
